server:
  port: 8091
# 应用名称
spring:
  application:
    name: shardingsphere-demo
  main:
    allow-bean-definition-overriding: true # 允许覆盖Bean
##############################################################################
#   shardingsphere 配置
##############################################################################
  shardingsphere:
    props:
      sql.show: true # 展示SQL
    datasource:
      names: ds1,ds2,ds3
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.33.51:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: master123
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.33.52:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: slave123
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.33.53:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: slave123
    sharding:
      default-data-source-name: ds1 # 默认数据源
    masterslave:
      name: ms # 配置主从名称
      master-data-source-name: ds1 # 主库
      slave-data-source-names: ds2,ds3 # 从库
      load-balance-algorithm-type: round_robin # 从节点负载均衡策略，轮询

##############################################################################
#   Mybatis 配置
##############################################################################
mybatis:
  mapper-locations: classpath:/mapper/*.xml

